services:
  gs-service:
    build: .
    image: constantin846/gs-service:v1  #  docker-compose -f docker-compose.yml up gs-service // up only this service
    container_name: gs-service
    ports:
      - "8080:8080"
    depends_on:
      - gs-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gs-db:5432/gs
      - SPRING_DATASOURCE_USERNAME=gs
      - SPRING_DATASOURCE_PASSWORD=gs
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
    volumes:
      - type: bind
        source: ./src/main/resources/optimized-product-price-scheduling/result.csv
        target: /src/main/resources/optimized-product-price-scheduling/result.csv

  gs-db:
    image: postgres:17
    container_name: postgres-gs-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=gs
      - POSTGRES_USER=gs
      - POSTGRES_DB=gs
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

