server:
  servlet.context-path: /gs
  port: ${SERVER_PORT:8080}


spring:
  datasource:
    driverClassName: org.postgersql.Driver
    url: jdbc:postgresql://db:5432/gs
    username: gs
    password: ${DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: validate
  database-platform: org.hibernate.dialect.PostgreSQL16Dialect

  liquibase:
    change-log: classpath:db/changelog/changelog-main.xml


app:
  scheduling:
    enable: true
    period: 60000 #ms
    priceIncreasePercentage: 10.1
    optimization:
      enable: true
      exclusive-lock: true #default true
  dbInit: false

logging:
  level:
    org.hibernate:
      SQL: INFO
      type: INFO
      orm.jdbc.bind: INFO