server:
  servlet.context-path: /gs
  port: ${SERVER_PORT:8080}


spring:
  datasource:
    driverClassName: org.postgersql.Driver
    url: jdbc:postgresql://db:5432/gs
    username: gs
    password: ${DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: validate
    # show-sql: true
    # properties.hibernate.format_sql: true
  database-platform: org.hibernate.dialect.PostgreSQL16Dialect

  liquibase:
    change-log: classpath:db/changelog/changelog-main.xml


app:
  scheduling:
    enable: true
    period: 60000 #ms
    priceIncreasePercentage: 10.1
    optimization:
      type: optimized-my # optimized # optimized-my
      exclusive-lock: false # doesn't work with h2
  dbInit: false
  currency-service.type: real # real # mock

currency-service:
  host: http://localhost:8088
  method:
    get-currencies: /app-currency/v1/currencies
  timeout: 2000 #ms

logging:
  level:
    org.hibernate:
      SQL: TRACE
      type: INFO
      orm.jdbc.bind: INFO