server.port: 8080


spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:gs;LOCK_TIMEOUT=60000
    username: gs
    password: ${DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: validate #create, update, none and validate
    database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true #http://localhost:8080/gs/h2-console

  liquibase:
    change-log: classpath:db/changelog/local-changelog-main.xml
    enabled: true
